development: &default
  secret_key_base: aff3a4d89b9c32c74467de9e0b27f8ff6485eeeb56886f18c411ca99af1e6415f6e55b9f73224c319501654ebdc08aa89579da8c9e71f8223f5aa2620953b766
  recaptcha_site_key: 6Ld8YAcaAAAAAICdzyStlbn0uujDp6Tv975t7cOI
  recaptcha_secret_key: 6Ld8YAcaAAAAAMOUQtQ5fVlOPWtCL8dWzaTjWlo2
  admin_username: 'admin'
  admin_password: 'password'
  mailgun_login: login
  mailgun_password: password
  tinypng_key: 3ayuylIGjF6wjdS5M7EypJ76ccR65_0y
prodoction:
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
test:
  <<: *default
